version: "3.3"

services:
  api:
    container_name: api-docker
    build: https://github.com/MeetMeTeam/MeetMe-Backend
    environment:
      APP_PORT: 8080
      APP_SECRET: "Hk89LSUPn3r4JDL@#@#$LJJKJDP00-.KJOS"
      MONGO_USERNAME: MeetMeUser
      MONGO_PASSWORD: Ntw171044
    ports:
      - '8080:8080'
    networks:
      - mynetwork
  web:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
  fe:
    container_name: react-docker
    build: https://github.com/MeetMeTeam/MeetMe-Frontend
    volumes:
      - '.././MeetMe-Frontend/:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_BASE_API=http://dev-meetme.com
      - REACT_APP_BASE_API_SOCKET=http://dev-meetme.com/socket
    networks:
      - mynetwork
  socket:
    container_name: socket-docker
    build: https://github.com/MeetMeTeam/MeetMe-Websocket
    volumes:
      - '.././MeetMe-Websocket/:/usr/src/app'
    ports:
      - '5002:5002'
    environment:
      API_PORT: 5002
      MONGO_URL: mongodb+srv://MeetMeUser:Ntw171044.@cluster0.salidj6.mongodb.net/?retryWrites=true&w=majority
      TOKEN_KEY: "Hk89LSUPn3r4JDL@#@#$LJJKJDP00-.KJOS"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge