name: Auto Deploy

on:
  push:
    branches:
    - dev
    - developer
    - main
  pull_request:
    branches:
    - dev
    - developer
    - main

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    container:
      image: lucasalt/act_base:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: "MeetMe-Deployment"
      - name: docker
        run: docker-compose up -d --build
